image: sejil/android:latest
variables:
  ANDROID_KEYSTORE_FILE: $ANDROID_KEYSTORE_FILE
  ANDROID_KEYSTORE_ALIAS: $ANDROID_KEYSTORE_ALIAS
  ANDROID_KEYSTORE_PASSWORD: $ANDROID_KEYSTORE_PASSWORD
  DIRECT_FILE_NAME: direct-${CI_COMMIT_SHORT_SHA}.apk
  DISCORD_URL: $DISCORD_URL

stages:
  - test
  - stage
  - release

# Run unit-tests
unitTest:
  interruptible: true
  stage: test
  script:
    - "echo 'ASAP: Write UNIT-TEST!!!'"
    - ./gradlew test

# Build stage version with stage endpoints
stageRelease:
  interruptible: true
  stage: stage
  script:
    - base64 -d $ANDROID_KEYSTORE_FILE > signed-key
    - ./gradlew assembleRelease
       -Pandroid.injected.signing.store.file=$(pwd)/signed-key
       -Pandroid.injected.signing.store.password="$ANDROID_KEYSTORE_PASSWORD"
       -Pandroid.injected.signing.key.alias="$ANDROID_KEYSTORE_ALIAS"
       -Pandroid.injected.signing.key.password="$ANDROID_KEYSTORE_PASSWORD"
    - mv app/build/outputs/apk/release/app-release.apk $DIRECT_FILE_NAME
    - |
      curl -isX POST -H "Accept: application/json" -H "Content-Type:application/json" \
        -d "{\"content\": \"New version of #Stage!\n\nReview and download apk:\n${CI_JOB_URL}\"}" \
        $DISCORD_URL > /dev/null
  artifacts:
    paths:
      - $DIRECT_FILE_NAME

# Build direct version with production endpoints
direct:
  interruptible: true
  stage: release
  script:
    - base64 -d $ANDROID_KEYSTORE_FILE > signed-key
    - ./gradlew assembleRelease
       -Pandroid.injected.signing.store.file=$(pwd)/signed-key
       -Pandroid.injected.signing.store.password="$ANDROID_KEYSTORE_PASSWORD"
       -Pandroid.injected.signing.key.alias="$ANDROID_KEYSTORE_ALIAS"
       -Pandroid.injected.signing.key.password="$ANDROID_KEYSTORE_PASSWORD"
    - mv app/build/outputs/apk/release/app-release.apk $DIRECT_FILE_NAME
    - |
      curl -isX POST -H "Accept: application/json" -H "Content-Type:application/json" \
        -d "{\"content\": \"New version of #Direct!\n\nReview and download apk:\n${CI_JOB_URL}\"}" \
        $DISCORD_URL > /dev/null
  artifacts:
    paths:
      - $DIRECT_FILE_NAME

